CREATE TABLE  users (

    user_id BIGINT  PRIMARY KEY AUTO_INCREMENT,

    name VARCHAR(100) NOT NULL,

    email VARCHAR(250) NOT NULL UNIQUE,

    password VARCHAR(255) NOT NULL UNIQUE,

    username VARCHAR(50) NOT NULL UNIQUE,



    phone VARCHAR(20),

    role_fk INT,

    FOREIGN KEY (role_fk) REFERENCES user_role(role_id)   ON DELETE CASCADE
    ON UPDATE CASCADE,

    profile_picture VARCHAR(355),

    gender ENUM('MALE', 'FEMALE') DEFAULT 'FEMALE',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);